### PR TITLE
ignore linkerd sidecar and add support for scanner tolerations

### PR DESCRIPTION
**Pull request by ronaldmiranda**
- ignore linkerd sidecar injection
- add suport for tolerations on scanner

### CODE REVIEW

**Comment by ronaldmirandazup** [comment]
@zayaanmoez can you help me with the approval of this request?

**Comment by zayaanmoez** [comment]
Hi @ronaldmirandazup,

Can I understand the use case for having tolerations on scanner pods?

**Comment by ronaldmiranda** [comment]
Hey @zayaanmoez thanks for answering me!

there are some cases that you have a kubernetes with nodes fully tainted with labels, in this case, i would have to set the tolerations for scanners, because the jobs will never run

**Comment by zayaanmoez** [comment]
Thank you @ronaldmirandazup. If the scanner pods have the tolerations inherited from the pod or deployment for which the image belongs, could that work? We are still discussing this requirement as we have some other use cases to consider.

For annotations, we will track task internally to have annotation support on the scanner pods through the helm values so that it can be applied beyond ignoring linkerd sidecar injection

**Comment by ronaldmiranda** [comment]
@zayaanmoez that could be interesting.

**Comment by zayaanmoez** [comment]
Hi @ronaldmiranda,

2.5.3 has been released with fixes for above issues:
https://github.com/trendmicro/cloudone-container-security-helm/releases/tag/2.5.3

For annotations, you can set the following overrides:
```
podAnnotations:
  scanner:
    linkerd.io/inject: disabled
```

To allow scanners to run on tainted nodes, you can set the following:
```
tolerations:
  inheritTolerationsScanner: true
```

For more details please see:
https://github.com/trendmicro/cloudone-container-security-helm?tab=readme-ov-file#configure-node-selectors-and-tolerations-for-the-container-security-components

**Pull request closed without merging**
